# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Weave < Formula
  desc "Cli tool for developing, testing, and running interwoven rollup"
  homepage "https://github.com/initia-labs/weave"
  url "https://github.com/initia-labs/weave/archive/refs/tags/v0.0.5.tar.gz"
  sha256 "820c45a72074663e9e05d763015583d7a559e28080c5983db7252a996cedeb8c"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/initia-labs/weave/releases/download/v0.0.5/weave-0.0.5-darwin-amd64.tar.gz"
      sha256 "3aea803689c39f55b2b19abe3f3ca7192d095bc26444470186a6507556cc0471"
    end

    on_arm do
      url "https://github.com/initia-labs/weave/releases/download/v0.0.5/weave-0.0.5-darwin-arm64.tar.gz"
      sha256 "5a426e56c23303acdc22b61ff2a6a1fd94e930a7f586de5eac7a19264acac1ba"
    end
  end

  def install
    bin.install "weave"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/weave version")
  end
end
