# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Weave < Formula
  desc "Cli tool for developing, testing, and running interwoven rollup"
  homepage "https://github.com/initia-labs/weave"
  url "https://github.com/initia-labs/weave/archive/refs/tags/v0.3.8.tar.gz"
  version "0.3.8"
  sha256 "306a832967f6212318e46ab4c73e20ffb4a8524195b0b497b749519b29b78220"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/initia-labs/weave/releases/download/v0.3.8/weave-0.3.8-darwin-amd64.tar.gz"
      sha256 "941bca71cffe5f12e009884ce3faf9b8df57b2c6e2e987ca455f526e9c4c85fb"
    end

    on_arm do
      url "https://github.com/initia-labs/weave/releases/download/v0.3.8/weave-0.3.8-darwin-arm64.tar.gz"
      sha256 "57f3aabcb9d01f5e70e76da46a01be67f0ab1d31d5e0f41f5f3e46b87c3fdac1"
    end
  end

  def install
    bin.install "weave"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/weave version")
  end
end
