# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Weave < Formula
  desc "Cli tool for developing, testing, and running interwoven rollup"
  homepage "https://github.com/initia-labs/weave"
  url "https://github.com/initia-labs/weave/archive/refs/tags/v0.1.3.tar.gz"
  version "0.1.3"
  sha256 "5d5fe60ff26030c1fa9ed94149d0f1619de3561bbdd67fba631ea3d29dc7627a"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/initia-labs/weave/releases/download/v0.1.3/weave-0.1.3-darwin-amd64.tar.gz"
      sha256 "04fc6056b6220bbb90c5e2352f44e6b8833085f366477c5225edf315636dbdaf"
    end

    on_arm do
      url "https://github.com/initia-labs/weave/releases/download/v0.1.3/weave-0.1.3-darwin-arm64.tar.gz"
      sha256 "8e635521568917fc3381c43b91026a7b54317355eb33013ce691682d06c46b20"
    end
  end

  def install
    bin.install "weave"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/weave version")
  end
end
